#!/bin/bash
echo "Installing service...";
touch /var/log/trailbot-watcher.log > /dev/null 2>&1 &&
(
# Systemd
if [ $(which systemd >/dev/null 2>&1) ]
then

cat > /etc/systemd/system/trailbot-watcher.service <<- EOM
[Unit]
Description=Trailbot Watcher
Wants=network-online.target
After=network.target network-online.target

[Service]
Type=simple
ExecStart=/bin/sh -c "$(pwd)/scripts/start >> /var/log/trailbot-watcher.log 2>&1"
Restart=always
User=root
Group=root
WorkingDirectory=$(pwd)

[Install]
WantedBy=multi.user.target
EOM
systemctl enable trailbot-watcher

else

# Upstart
if [ $(which upstart >/dev/null 2>&1) ]
then

cat > /etc/init/trailbot-watcher.conf <<- EOM
#!upstart
description "Trailbot Watcher"

respawn

start on (local-filesystems and net-device-up IFACE!=lo)
stop on shutdown

script
  chdir $(pwd)
  exec /bin/sh -c "$(pwd)/scripts/start >> /var/log/trailbot-watcher.log 2>&1"
end script
EOM
chmod +x /etc/init/trailbot-watcher.conf

# System V
else

cat > /etc/init.d/trailbot-watcher <<- EOM
#!/bin/bash
#
# trailbot-watcher        Start up Trailbot Watcher
#
# chkconfig: 2345 55 25
# processname: trailbot-watcher
# pidfile: /var/run/trailbot-watcher.pid

### BEGIN INIT INFO
# Provides: trailbot-watcher
# Required-Start: \$local_fs \$network \$syslog
# Required-Stop: \$local_fs \$syslog
# Should-Start: \$syslog
# Should-Stop: \$network \$syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
### END INIT INFO

# Source function library.
. /etc/init.d/functions

PIDFILE="/var/run/trailbot-watcher.pid"

start() {
  cd $(pwd)
  /bin/sh -c $(pwd)/scripts/start >> /var/log/trailbot-watcher.log 2>&1 &
  echo \$! > \$PIDFILE
}

stop() {
  killproc -p \$PIDFILE >/dev/null 2>&1
}

case "\$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload|force-reload)
    stop
    start
    ;;
  *)
    echo \$"Usage: \$0 {start|stop|restart|reload|force-reload}"
    exit 2
esac

EOM
chmod +x /etc/init.d/trailbot-watcher

fi
fi
) && (
service trailbot-watcher restart &&
echo "Trailbot Watcher is now up and running!"
) || echo -e "\e[01;31mERROR: Could not install service.\e[0m"
